{
 "title": "Jobs Overview",
 "tags": [
  "nebius",
  "soperator",
  "overview",
  "jobs"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "min_workers_per_job", "label": "Min worker count", "query": "1" },
   {
    "name": "slurm_job",
    "label": "Jobs",
    "query": {
     "query": "query_result(count by (job_id) (slurm_job_info{user_name!=\"soperatorchecks\"}))"
    }
   },
   {
    "name": "worker",
    "label": "Workers",
    "query": {
     "query": "label_values(DCGM_FI_DEV_GPU_TEMP{hpc_job=~\"$slurm_job\"},exported_pod)"
    }
   },
   {
    "name": "hostname",
    "label": "instance",
    "query": {
     "query": "label_values(kube_pod_info{pod=~\"$worker\"},node)"
    }
   },
   {
    "name": "ip",
    "label": "ip",
    "query": {
     "query": "label_values(node_uname_info{container=\"node-exporter\", nodename=~\"$hostname\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Quick Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Usage Guide",
   "type": "text",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "options": {
    "content": "* You can select multiple Jobs, list of Workers will be filtered based on that, only one of the jobs is selected by default\n* You can select multiple Workers, All are selected by default\n* Stats in all panels will be based on selected Jobs and Workers\n* check per worker stats below when there are large variance in cluster level stats, or when you want to spot outlier workers\n"
   }
  },
  {
   "title": "CPU",
   "type": "stat",
   "description": "Avg of utilization across all selected workers and instances",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg (\n  (1 - rate(node_cpu_seconds_total{mode=\"idle\"}[1m]))\n  * on(instance) group_left(nodename) node_uname_info\n  * on(nodename) group_left(hpc_job) clamp_max(clamp_min(count by(nodename, hpc_job) (label_replace(DCGM_FI_DEV_GPU_TEMP{hpc_job=~\"$slurm_job\"}, \"nodename\", \"$1\", \"Hostname\", \".*\")), 1), 1)\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU SM Clocks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_SM_CLOCK{exported_pod=~\"$worker\",hpc_job=~\"$slurm_job\"}*1000000)"
    }
   ]
  },
  {
   "title": "GPU Power Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_POWER_USAGE{exported_pod=~\"$worker\",hpc_job=~\"$slurm_job\"})"
    }
   ]
  },
  {
   "title": "GPU Avg. Mem. Cpy Utilization",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_MEM_COPY_UTIL{exported_pod=~\"$worker\",hpc_job=~\"$slurm_job\"})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(\n    (\n        node_memory_MemTotal_bytes - \n        node_memory_MemFree_bytes  - \n        node_memory_Buffers_bytes - \n        node_memory_Cached_bytes\n    ) / \n    node_memory_MemTotal_bytes{instance=~\"$ip\"}\n    * on(instance) group_left(nodename) node_uname_info\n    * on(nodename) group_left(hpc_job) clamp_max(clamp_min(count by(nodename, hpc_job) (label_replace(DCGM_FI_DEV_GPU_TEMP{hpc_job=~\"$slurm_job\"}, \"nodename\", \"$1\", \"Hostname\", \".*\")), 1), 1)\n) * 100"
    }
   ]
  },
  {
   "title": "GPU Mem Clock",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_MEM_CLOCK{exported_pod=~\"$worker\",hpc_job=~\"$slurm_job\"}*1000000)"
    }
   ]
  },
  {
   "title": "GPU Total Utilization",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_UTIL{exported_pod=~\"$worker\",hpc_job=~\"$slurm_job\"})"
    }
   ]
  },
  {
   "title": "GPU Avg. Temp",
   "type": "stat",
   "description": "GPU Shutdown Temp: 90 C<br>\nGPU Slowdown Temp: 87 C<br>\nGPU Max Operating Temp: 83 C<br>",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_TEMP{exported_pod=~\"$worker\",hpc_job=~\"$slurm_job\"})"
    }
   ]
  },
  { "title": "Jobs Timeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Job Details",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "\nslurm_job_info{job_id=~\"$slurm_job\"}\n* on (job_id) group_left()\ncount by(job_id) (slurm_node_job{job_id=~\"$slurm_job\"}) "
    }
   ]
  },
  {
   "title": "Job State Timeline",
   "type": "state-timeline",
   "description": "Paginated",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "\nsum by(job_id)(\n  count by(job_id, job_name) (slurm_job_info{job_state=\"PENDING\", job_id=~\"$slurm_job\"}) * 1 or\n  count by(job_id, job_name) (slurm_job_info{job_state=\"CONFIGURING\", job_id=~\"$slurm_job\"}) * 2 or\n  count by(job_id, job_name) (slurm_job_info{job_state=\"RUNNING\", job_id=~\"$slurm_job\"}) * 3 or\n  count by(job_id, job_name) (slurm_job_info{job_state=\"COMPLETING\", job_id=~\"$slurm_job\"}) * 4 or\n  count by(job_id, job_name) (slurm_job_info{job_state=\"COMPLETED\", job_id=~\"$slurm_job\"}) * 5 or\n  count by(job_id, job_name) (slurm_job_info{job_state=\"CANCELLED\", job_id=~\"$slurm_job\"}) * 6 or\n  count by(job_id, job_name) (slurm_job_info{job_state=\"FAILED\", job_id=~\"$slurm_job\"}) * 7 or\n  count by(job_id, job_name) (slurm_job_info{job_state=\"TIMEOUT\", job_id=~\"$slurm_job\"}) * 8 or\n  count by(job_id, job_name) (slurm_job_info{job_state=\"PREEMPTED\", job_id=~\"$slurm_job\"}) * 9 or\n  count by(job_id, job_name) (slurm_job_info{job_state=\"NODE_FAIL\", job_id=~\"$slurm_job\"}) * 10 or\n  count by(job_id, job_name) (slurm_job_info{job_state=\"BOOT_FAIL\", job_id=~\"$slurm_job\"}) * 11 or\n  count by(job_id, job_name) (slurm_job_info{job_state=\"DEADLINE\", job_id=~\"$slurm_job\"}) * 12 or\n  count by(job_id, job_name) (slurm_job_info{job_state=\"OUT_OF_MEMORY\", job_id=~\"$slurm_job\"}) * 13 or\n  count by(job_id, job_name) (slurm_job_info{job_state=\"REQUEUED\", job_id=~\"$slurm_job\"}) * 14 or\n  count by(job_id, job_name) (slurm_job_info{job_state=\"RESIZING\", job_id=~\"$slurm_job\"}) * 15 or\n  count by(job_id, job_name) (slurm_job_info{job_state=\"SUSPENDED\", job_id=~\"$slurm_job\"}) * 16 or\n  count by(job_id, job_name) (slurm_job_info{job_state=\"STOPPED\", job_id=~\"$slurm_job\"}) * 17 or\n  count by(job_id, job_name) (slurm_job_info{job_state=\"POWER_UP_NODE\", job_id=~\"$slurm_job\"}) * 18 or\n  count by(job_id, job_name) (slurm_job_info{job_state=\"SIGNALING\", job_id=~\"$slurm_job\"}) * 19 or\n  count by(job_id, job_name) (slurm_job_info{job_state=\"STAGE_OUT\", job_id=~\"$slurm_job\"}) * 20 or\n  count by(job_id, job_name) (slurm_job_info{job_state=\"UPDATE_DB\", job_id=~\"$slurm_job\"}) * 21\n)",
     "legendFormat": "{{job_id}}"
    }
   ]
  },
  {
   "title": "Cluster Overall Stats (for selected Jobs and Workers)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(DCGM_FI_DEV_GPU_UTIL{exported_pod=~\"$worker\",hpc_job=~\"$slurm_job\"})",
     "legendFormat": "max"
    },
    {
     "expr": "avg(DCGM_FI_DEV_GPU_UTIL{exported_pod=~\"$worker\",hpc_job=~\"$slurm_job\"})",
     "legendFormat": "avg"
    },
    {
     "expr": "min(DCGM_FI_DEV_GPU_UTIL{exported_pod=~\"$worker\",hpc_job=~\"$slurm_job\"})",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "GPU Theoretical FLOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "tflops" } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{exported_pod=~\"$worker\",hpc_job=~\"$slurm_job\"} * 1979)",
     "legendFormat": "FP8"
    },
    {
     "expr": "sum(DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{exported_pod=~\"$worker\",hpc_job=~\"$slurm_job\"} * 989.7)",
     "legendFormat": "FP16/BF16"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max (DCGM_FI_DEV_GPU_TEMP{exported_pod=~\"$worker\",hpc_job=~\"$slurm_job\"})",
     "legendFormat": "max"
    },
    {
     "expr": "avg (DCGM_FI_DEV_GPU_TEMP{exported_pod=~\"$worker\",hpc_job=~\"$slurm_job\"})",
     "legendFormat": "avg"
    },
    {
     "expr": "min (DCGM_FI_DEV_GPU_TEMP{exported_pod=~\"$worker\",hpc_job=~\"$slurm_job\"})",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(\n  (1 - rate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$ip\"}[$__rate_interval]))\n  * on(instance) group_left(nodename) node_uname_info\n  * on(nodename) group_left(hpc_job) clamp_max(clamp_min(count by(nodename, hpc_job) (label_replace(DCGM_FI_DEV_GPU_TEMP{hpc_job=~\"$slurm_job\"}, \"nodename\", \"$1\", \"Hostname\", \".*\")), 1), 1)\n)",
     "legendFormat": "max"
    },
    {
     "expr": "avg(\n  (1 - rate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$ip\"}[$__rate_interval]))\n  * on(instance) group_left(nodename) node_uname_info\n  * on(nodename) group_left(hpc_job) clamp_max(clamp_min(count by(nodename, hpc_job) (label_replace(DCGM_FI_DEV_GPU_TEMP{hpc_job=~\"$slurm_job\"}, \"nodename\", \"$1\", \"Hostname\", \".*\")), 1), 1)\n)",
     "legendFormat": "avg"
    },
    {
     "expr": "min(\n  (1 - rate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$ip\"}[$__rate_interval]))\n  * on(instance) group_left(nodename) node_uname_info\n  * on(nodename) group_left(hpc_job) clamp_max(clamp_min(count by(nodename, hpc_job) (label_replace(DCGM_FI_DEV_GPU_TEMP{hpc_job=~\"$slurm_job\"}, \"nodename\", \"$1\", \"Hostname\", \".*\")), 1), 1)\n)",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "GPU Mem Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(DCGM_FI_DEV_FB_USED{exported_pod=~\"$worker\",hpc_job=~\"$slurm_job\"}/(DCGM_FI_DEV_FB_USED{exported_pod=~\"$worker\",hpc_job=~\"$slurm_job\"}+DCGM_FI_DEV_FB_FREE{exported_pod=~\"$worker\",hpc_job=~\"$slurm_job\"}))",
     "legendFormat": "max"
    },
    {
     "expr": "avg(DCGM_FI_DEV_FB_USED{exported_pod=~\"$worker\",hpc_job=~\"$slurm_job\"}/(DCGM_FI_DEV_FB_USED{exported_pod=~\"$worker\",hpc_job=~\"$slurm_job\"}+DCGM_FI_DEV_FB_FREE{exported_pod=~\"$worker\",hpc_job=~\"$slurm_job\"}))",
     "legendFormat": "avg"
    },
    {
     "expr": "min(DCGM_FI_DEV_FB_USED{exported_pod=~\"$worker\",hpc_job=~\"$slurm_job\"}/(DCGM_FI_DEV_FB_USED{exported_pod=~\"$worker\",hpc_job=~\"$slurm_job\"}+DCGM_FI_DEV_FB_FREE{exported_pod=~\"$worker\",hpc_job=~\"$slurm_job\"}))",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "Infiniband Throughput",
   "type": "timeseries",
   "description": "Sum of Tx and Rx for all selected Workers ",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(\n  rate(node_infiniband_port_data_transmitted_bytes_total{instance=~\"$ip\"}[$__interval])\n  * on(instance) group_left(nodename) node_uname_info\n  * on(nodename) group_left(hpc_job) clamp_max(clamp_min(count by(nodename, hpc_job) (label_replace(DCGM_FI_DEV_GPU_TEMP{hpc_job=~\"$slurm_job\"}, \"nodename\", \"$1\", \"Hostname\", \".*\")), 1), 1)\n)",
     "legendFormat": "Tx"
    },
    {
     "expr": "sum(\n  rate(node_infiniband_port_data_received_bytes_total{instance=~\"$ip\"}[$__interval])\n  * on(instance) group_left(nodename) node_uname_info\n  * on(nodename) group_left(hpc_job) clamp_max(clamp_min(count by(nodename, hpc_job) (label_replace(DCGM_FI_DEV_GPU_TEMP{hpc_job=~\"$slurm_job\"}, \"nodename\", \"$1\", \"Hostname\", \".*\")), 1), 1)\n)",
     "legendFormat": "Rx {{pod}}"
    }
   ]
  },
  {
   "title": "System Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(\n  (\n    (\n      node_memory_MemTotal_bytes - \n      node_memory_MemFree_bytes - \n      node_memory_Buffers_bytes - \n      node_memory_Cached_bytes\n    )\n    /\n    node_memory_MemTotal_bytes{instance=~\"$ip\"}\n  )\n  * on(instance) group_left(nodename) node_uname_info\n  * on(nodename) group_left(hpc_job) clamp_max(clamp_min(count by(nodename, hpc_job) (label_replace(DCGM_FI_DEV_GPU_TEMP{hpc_job=~\"$slurm_job\"}, \"nodename\", \"$1\", \"Hostname\", \".*\")), 1), 1)\n)",
     "legendFormat": "max"
    },
    {
     "expr": "avg(\n  (\n    (\n      node_memory_MemTotal_bytes - \n      node_memory_MemFree_bytes - \n      node_memory_Buffers_bytes - \n      node_memory_Cached_bytes\n    )\n    /\n    node_memory_MemTotal_bytes{instance=~\"$ip\"}\n  )\n  * on(instance) group_left(nodename) node_uname_info\n  * on(nodename) group_left(hpc_job) clamp_max(clamp_min(count by(nodename, hpc_job) (label_replace(DCGM_FI_DEV_GPU_TEMP{hpc_job=~\"$slurm_job\"}, \"nodename\", \"$1\", \"Hostname\", \".*\")), 1), 1)\n)",
     "legendFormat": "avg"
    },
    {
     "expr": "min(\n  (\n    (\n      node_memory_MemTotal_bytes - \n      node_memory_MemFree_bytes - \n      node_memory_Buffers_bytes - \n      node_memory_Cached_bytes\n    )\n    /\n    node_memory_MemTotal_bytes{instance=~\"$ip\"}\n  )\n  * on(instance) group_left(nodename) node_uname_info\n  * on(nodename) group_left(hpc_job) clamp_max(clamp_min(count by(nodename, hpc_job) (label_replace(DCGM_FI_DEV_GPU_TEMP{hpc_job=~\"$slurm_job\"}, \"nodename\", \"$1\", \"Hostname\", \".*\")), 1), 1)\n)",
     "legendFormat": "min"
    }
   ]
  },
  { "title": "GPU Stats per Worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "GPU Avg Utilization per Worker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(exported_pod) (DCGM_FI_DEV_GPU_UTIL{exported_pod=~\"$worker\",hpc_job=~\"$slurm_job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Avg Mem Usage per Worker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(exported_pod) (DCGM_FI_DEV_FB_USED{exported_pod=~\"$worker\",hpc_job=~\"$slurm_job\"}/(DCGM_FI_DEV_FB_USED{exported_pod=~\"$worker\",hpc_job=~\"$slurm_job\"}+DCGM_FI_DEV_FB_FREE{exported_pod=~\"$worker\",hpc_job=~\"$slurm_job\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Avg Mem Copy Utilization per Worker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(exported_pod) (DCGM_FI_DEV_MEM_COPY_UTIL{exported_pod=~\"$worker\",hpc_job=~\"$slurm_job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Total Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum by(exported_pod) (DCGM_FI_DEV_POWER_USAGE{exported_pod=~\"$worker\",hpc_job=~\"$slurm_job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Avg Temperature per Worker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by(exported_pod) (DCGM_FI_DEV_GPU_TEMP{exported_pod=~\"$worker\",hpc_job=~\"$slurm_job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "XID errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 54 },
   "targets": [
    {
     "expr": "sum by(err_msg, exported_pod) (rate(DCGM_FI_DEV_XID_ERRORS{exported_pod=~\"$worker\",hpc_job=~\"$slurm_job\"}[$__rate_interval]))",
     "legendFormat": "{{exported_pod}}: {{err_msg}}"
    }
   ]
  }
 ]
}