{
 "title": "NFS Server & Client",
 "tags": [
  "nebius",
  "soperator",
  "nfs"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "compute_instance",
    "label": "Compute instance",
    "query": {
     "query": "label_values(kube_pod_info{}, node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Server Threads",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_nfsd_server_threads{   namespace=\"nfs-system\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NFS server disk usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{\n    persistentvolumeclaim=\"nfs-server-storage\"\n}\n/\nkubelet_volume_stats_capacity_bytes{\n    persistentvolumeclaim=\"nfs-server-storage\"\n}"
    }
   ]
  },
  {
   "title": "NFS server disk size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_capacity_bytes{\n    persistentvolumeclaim=\"nfs-server-storage\"\n}"
    }
   ]
  },
  {
   "title": "NFS Client RPC Retransmissions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cluster) (rate(node_nfs_rpc_retransmissions_total{  }[$__rate_interval]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "NFS Client Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "NFS Client RPCs",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_nfs_rpcs_total{  }[$__rate_interval])\n* on(cluster, pod) group_left(node)\nkube_pod_info{  node=~\"$compute_instance\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "NFS Client RPC Retransmissions",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_nfs_rpc_retransmissions_total{  }[$__rate_interval])\n* on(cluster, pod) group_left(node)\nkube_pod_info{  node=~\"$compute_instance\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "NFS Client Requests by Method",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  rate(node_nfs_requests_total{  proto=\"4\"}[$__rate_interval])\n  * on(cluster, pod) group_left(node)\n  kube_pod_info{  node=~\"$compute_instance\"}\n) by(method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  { "title": "NFS Server Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "NFSd Disk Read / Write",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_nfsd_disk_bytes_read_total{   namespace=\"nfs-system\"}[$__rate_interval])",
     "legendFormat": "NFSd bytes read"
    },
    {
     "expr": "rate(node_nfsd_disk_bytes_written_total{   namespace=\"nfs-system\"}[$__rate_interval])",
     "legendFormat": "NFSd bytes written"
    }
   ]
  },
  {
   "title": "NFSd Packets",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_nfsd_packets_total{proto=\"tcp\",   namespace=\"nfs-system\"}[$__rate_interval])",
     "legendFormat": "TCP - NFSd network packets (sent+received)"
    },
    {
     "expr": "rate(node_nfsd_packets_total{proto=\"udp\",   namespace=\"nfs-system\"}[$__rate_interval])",
     "legendFormat": "UDP - NFSd network packets (sent+received)"
    }
   ]
  },
  {
   "title": "NFS Cache",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_nfsd_read_ahead_cache_not_found_total{ namespace=\"nfs-system\" }[$__rate_interval])",
     "legendFormat": "NFSd read ahead cache not found"
    },
    {
     "expr": "rate(node_nfsd_reply_cache_hits_total{ namespace=\"nfs-system\" }[$__rate_interval])",
     "legendFormat": "NFSd Reply Cache hits (client lost server response)"
    },
    {
     "expr": "rate(node_nfsd_reply_cache_misses_total{ namespace=\"nfs-system\" }[$__rate_interval])",
     "legendFormat": "NFSd Reply Cache an operation that requires caching (idempotent)"
    },
    {
     "expr": "rate(node_nfsd_reply_cache_nocache_total{ namespace=\"nfs-system\" }[$__rate_interval])",
     "legendFormat": "NFSd Reply Cache non-idempotent operations (rename/delete/…)"
    }
   ]
  },
  {
   "title": "NFSd RPC",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_nfsd_rpc_errors_total{ namespace=\"nfs-system\" }[$__rate_interval])",
     "legendFormat": "{{ error }} - NFSd RPC errors"
    },
    {
     "expr": "rate(node_nfsd_server_rpcs_total{ namespace=\"nfs-system\" }[$__rate_interval])",
     "legendFormat": "NFSd RPCs"
    }
   ]
  },
  {
   "title": "NFS Server Requests by Method",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_nfsd_requests_total{proto=\"4\",  namespace=\"nfs-system\" }[$__rate_interval])",
     "legendFormat": "{{ method }}"
    }
   ]
  }
 ]
}